on:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_ENVIRONMENT_NAME: calculadora-seguro-api
  RESOURCE_GROUP: jeff-lab
  CONTAINER_REGISTRY_NAME: registry20240827150651
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20240827150651.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
        - appsourcepath: src/CalculadoraSeguros.API
          containerappname: calculadoraseguros.api-container-app
        - appsourcepath: src/CalculadoraSeguros.UI
          containerappname: calculadoraseguros.ui-container-app
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.calculadora_seguro_api_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}/${{ matrix.appsourcepath }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.registry20240827150651_USERNAME_708F }}
        acrPassword: ${{ secrets.registry20240827150651_PASSWORD_708F }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ matrix.containerappname }}:${{ github.sha }}
        containerAppName: ${{ matrix.containerappname }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
